require 'rubygems'
require 'rake'

require 'rake/testtask'

dir = File.dirname(__FILE__)

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.test_files = Dir.glob("#{dir}/test/cases/**/*_test.rb").sort
  t.warning = true
end

require 'rake/packagetask'
require 'rake/gempackagetask'

spec = eval(File.read('omega.gemspec'))

Rake::GemPackageTask.new(spec) do |p|
  p.gem_spec = spec
end

desc 'Release to gemcutter'
task :release => :package do
  require 'rake/gemcutter'
  Rake::Gemcutter::Tasks.new(spec).define
  Rake::Task['gem:push'].invoke
end

version = File.read(File.expand_path('../../VERSION', __FILE__)).strip

desc 'Install gem'
task :install => :gem do
  system("gem install pkg/omega-#{version}.gem --no-ri --no-rdoc")
end
