require 'rubygems'
require 'rake'
require 'rake/packagetask'
require 'rake/gempackagetask'

spec = eval(File.read('omegavolunteering.gemspec'))
Rake::GemPackageTask.new(spec) do |p|
  p.gem_spec = spec
end

desc "Install gem"
task :install => :gem do
  system("gem install pkg/omegavolunteering-0.0.1.gem --no-ri --no-rdoc")
end
